# Generated by Django 6.1 on 2026-08-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('category', models.CharField(choices=[('health', 'Health'), ('work', 'Work'), ('learning', 'Learning'), ('fitness', 'Fitness'), ('mental_health', 'Mental Health'), ('productivity', 'Productivity')], default='health', max_length=20)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
